import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

import { Provider } from "react-redux";
import store from "./store";
import ReduxProvider from "./store/redux-provider";
const kanit = Kanit({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Your ToDo List",
  description: "Generated by Igor Malov",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>

    </html>
  );
}
